### ISSUE TITLE
Tag field

### ISSUE THREAD

**Issue by xtimon** [MickayG/moby-kafka-logdriver#6]
It would be great if you'll add a tag field to messages.

**Comment by xtimon** [comment]
Example of the use case:
```
version: '2'

services:

  test-kafka-work:
    image: busybox
    environment:
      - "LOG_TAG=testing"
    command: /bin/sh -c "while true; do echo hello world; sleep 1; done"
    logging:
      driver: mickyg/kafka-logdriver:latest
```
